# Stop and unregister every Windows Scheduled Task generated by start-windows.ps1.
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $scriptDir

if ($env:OS -ne "Windows_NT") {
    throw "stop-windows.ps1 must be run on a Windows host."
}

$TaskFolder = "\GitHubSelfHostedRunner\"
$taskDir = ".runner-windows\scheduled-tasks"
$slotsDir = ".runner-windows\slots"

if (-not (Test-Path -LiteralPath $taskDir -PathType Container)) {
    Write-Host "No generated Windows runner tasks were found."
    exit 0
}

function Wait-TaskStopped {
    param([string]$Name)
    for ($attempt = 1; $attempt -le 30; $attempt++) {
        $task = Get-ScheduledTask -TaskName $Name -TaskPath $TaskFolder -ErrorAction SilentlyContinue
        if ($null -eq $task -or $task.State -ne "Running") {
            return $true
        }
        Start-Sleep -Seconds 1
    }
    return $false
}

$stopped = 0
$xmlFiles = Get-ChildItem -LiteralPath $taskDir -Filter "*.xml" -ErrorAction SilentlyContinue
foreach ($xmlFile in $xmlFiles) {
    $name = $xmlFile.BaseName
    $task = Get-ScheduledTask -TaskName $name -TaskPath $TaskFolder -ErrorAction SilentlyContinue
    if ($null -eq $task) {
        continue
    }

    $slotDir = Join-Path $slotsDir $name
    if (Test-Path -LiteralPath $slotDir) {
        New-Item -ItemType File -Force -Path (Join-Path $slotDir "stop.flag") | Out-Null
    }
    if (-not (Wait-TaskStopped -Name $name)) {
        Write-Warning "$name did not stop gracefully within 30 seconds; unregistering anyway."
    }
    Unregister-ScheduledTask -TaskName $name -TaskPath $TaskFolder -Confirm:$false -ErrorAction SilentlyContinue
    $stopped++
}

if ($stopped -eq 0) {
    Write-Host "No registered Windows runner tasks were found."
} else {
    Write-Host "Stopped $stopped Windows runner task(s)."
}
