#!/usr/bin/env bash
# Unload every macOS launchd agent generated by start-macos.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

if [ "$(uname -s)" != "Darwin" ]; then
    echo "Error: stop-macos.sh must be run on a macOS host." >&2
    exit 1
fi

launchd_dir=".runner-macos/launchd"
if [ ! -d "${launchd_dir}" ]; then
    echo "No generated macOS runner agents were found."
    exit 0
fi

uid="$(id -u)"
stopped=0
launchagents_dir="${HOME}/Library/LaunchAgents"
shopt -s nullglob
for plist in "${launchd_dir}"/*.plist; do
    label="$(basename "${plist}" .plist)"
    if launchctl bootout "gui/${uid}/${label}" >/dev/null 2>&1; then
        stopped=$((stopped + 1))
    fi
    rm -f -- "${launchagents_dir}/${label}.plist"
done

if [ "${stopped}" -eq 0 ]; then
    echo "No loaded macOS runners were found."
else
    echo "Stopped ${stopped} macOS runner agent(s)."
fi
